### ISSUE TITLE
no  gibberwocky_tutorial_1-4 max patcher included

### ISSUE THREAD

**Issue by vichug** [worldmaking/max_gibberwocky_package#1]
copy pasting from the c74 forum thread : 
 in the demos of the gibberwocky script editor, "tutorial 1 : basic messaging" it says :  
```
* To start make sure you open the patch: 
* gibberwocky_tutorial_1-4
```
but there doesn't appear to be such a  patcher inside the gibberwocky max package

**Comment by vichug** [comment]
mm, maybe the gibberwocky.maxhelp is supposed to replace the tuto, but the bass device can't do harmonies, so it's not ideal

**Comment by grrrwaaa** [comment]
Hey Vichug,

Yes, the help patcher is supposed to replace the tutorial patcher -- the comments were left in by mistake.

The bass device can do harmonies, just needs the Voices number increased. Or, from Gibberwocky, ```devices['bass']['polyphony’](4)```. We should probably just set that as a default in the help patcher.

Not the most ideal pitched instrument perhaps but there's not a huge selection from the devices that come with Max...

G

**Comment by vichug** [comment]
Oh, didn't see that voices number in the bass device ! ty!

**Comment by charlieroberts** [comment]
OK, this is all fixed now, as the bass instrument is set to be polyphonic by default and the example has been updated to not reference the old 1-4 tutorial.
